CREATE TABLE soueu (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(20),
    mensagem TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);